/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/edit-profile` | `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/new-chat` | `/new-chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/subscription` | `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/chat/[id]` | `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(protected)'}${'/(modals)'}/story/[id]` | `/story/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/edit-profile` | `/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/new-chat` | `/new-chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/subscription` | `/subscription`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/chat/[id]` | `/chat/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(protected)'}${'/(modals)'}/story/[id]` | `/story/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(modals)'}/edit-profile${`?${string}` | `#${string}` | ''}` | `/edit-profile${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(modals)'}/new-chat${`?${string}` | `#${string}` | ''}` | `/new-chat${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(modals)'}/subscription${`?${string}` | `#${string}` | ''}` | `/subscription${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/edit-profile` | `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/new-chat` | `/new-chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(modals)'}/subscription` | `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `${'/(protected)'}${'/(modals)'}/chat/${Router.SingleRoutePart<T>}` | `/chat/${Router.SingleRoutePart<T>}` | `${'/(protected)'}${'/(modals)'}/story/${Router.SingleRoutePart<T>}` | `/story/${Router.SingleRoutePart<T>}` | { pathname: `${'/(protected)'}${'/(modals)'}/chat/[id]` | `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(protected)'}${'/(modals)'}/story/[id]` | `/story/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
